### PR TITLE
add bare tracker map in order to be able to make TPolyLine-based Strip detector maps

### PR DESCRIPTION
**Pull request by mmusich**
title says it all.

### CODE REVIEW

**Comment by mmusich** [comment]
@smuzaffar, @andrius-k, @kmaeshima, @schneiml, @mrodozov, @jfernan2, @fioriNTU, @tulamor

what is the procedure to include this file in the data repo? It is not (yet) used in cmssw, but as soon as it will be available, I plan to consume it.

**Comment by mrodozov** [comment]
Once you have the cmssw part that uses it, we test both PRs together until the cmssw part is using this data file in an acceptable way. the test doesn't require merge of this PR so don't worry about that

**Comment by mrodozov** [comment]
and maybe have an extension for that file .dat .txt .json etc, whatever the format is

**Comment by mmusich** [comment]
@mrodozov I'd actually like to have this file merged in the data-repo before providing the code in cmssw as there are already standalone application that can use it. Is that possible?
Also there are other files in the repo without any extentions. I'd rather leave it as it is.

**Comment by mrodozov** [comment]
please test
new data files can be added as they don't break anything, yes.

**Comment by mmusich** [comment]
@smuzaffar, @andrius-k, @kmaeshima, @schneiml, @mrodozov, @jfernan2, @fioriNTU, @tulamor

This PR has been sitting idle for 10 days now, can we please move on with this it? 
Please let me know if there is anything I can do.

**Comment by jfernan2** [comment]
@mmusich there is nothing DQM team can do about this PR, I am afraid cms-data belongs to Core software

**Comment by smuzaffar** [comment]
As it is a new file so there is nothing blocking it. We just want to make sure that you are happy with the content of the changes by testing them in cmssw first. That is why we always ask for a test in cmssw for such changes.

@jfernan2 , consider cms-data repositories as part of cmssw packages. There is one to one mapping between cmssw package and cms-data repos. If DQM is responsible for DQM/SiStripMonitorClient cmssw package then they are also responsible for DQM-SiStripMonitorClient data repo. If you are happy with the change here then please sign it and we will integrate it for next IB.

**Comment by mmusich** [comment]
> @mmusich there is nothing DQM team can do about this PR, I am afraid cms-data belongs to Core software

@jfernan2 then why is the PR dqm-pending?
image

**Comment by jfernan2** [comment]
+1
I am sorry @smuzaffar @mmusich  but I was not aware of this, however how can I say if I am happy with the change if it has not being tested and it is data file? 
Moreover, I see that 90% of the PRs in cms-data have been closed without signing, could you explain me how can I know that this should be indeed signed?

**Comment by smuzaffar** [comment]
90% might be too exaggerated :-) most of data externals are signed. Those, which are not signed directly on data external,  are signed via corresponding cmssw PR (which was used to test it).

You should not sign it if there are no tests run. You should ask the question to auther what is the purpose if this and how this has been validation

**Comment by mmusich** [comment]
@jfernan2 @smuzaffar 
so if you really want me to release the CMSSW code, I can make the PR but I would still need to work on it, in the meanwhile you can look at it here: https://github.com/cms-sw/cmssw/compare/master...mmusich:TrackerRemapper_11_2_X?expand=1.
As I mentioned earlier there are certain standalone applications (outside of cmssw) that can use this, so that's why I wanted to make the file available first.
As for validation see please attached plot 

image

which is obtained by running the cfg file example in the branch

**Comment by jfernan2** [comment]
@smuzaffar  Yes, 90% may be exagerated globally :-) but the packages I glimpsed were 90%....
@mmusich if you are happy with the data file, so am I

**Comment by smuzaffar** [comment]
+externals

**Comment by smuzaffar** [comment]
today's 11h00 IB will include this.

**Comment by mmusich** [comment]
thanks @smuzaffar !

**Pull request merged**
